---
#########################################
#
# author : Gharios Damien
# date : 07-2020
# enterprise : Donow
#
#########################################
# Playbook Ansible

- name: Déploiement d'une conf NginX pour Docker-compose
  hosts: web
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
   - include_vars: roles/vars_conf.yml  
   - name: Ajout du template de conf dans NginX conf.d
     become: true
     template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_dir }}/{{ server_name }}.conf"
                
   - name: Ajout du site dans /etc/hosts
     become: true
     lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"
  
   - name: Créer et démarrer le service docker compose
     docker_compose:
        project_src: "{{ docker_dir }}"
        state: present
        build: yes
     register: output
   - debug: 
        var: output
        
   - name: Relancer le service NginX
     become: true
     service:
        name: nginx
        state: restarted
