---
- name: Configuration de NginX
  hosts: web
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars:
    ansible_ssh_private_key_file: acces_aws.pem
  #connection: local
  #vars:
  #      server_name: test.nginx.lb #à renseigner
  #      proxy_pass: http://localhost:8085 #à renseigner
  #      nginx_dir: /etc/nginx/conf.d

  tasks:
   - include_vars: roles/vars_conf.yml  
   - name: Ajout du template de conf dans NginX conf.d
     become: true
     template:
        src: templates/test-nginx.conf
        dest: "{{ nginx_dir }}/{{ server_name }}.conf"
                
   - name: Ajout du site dans /etc/hosts
     become: true
     lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"
  
   - name: Créer et démarrer le service docker compose
     docker_compose:
        project_src: "{{ docker_dir }}"
        build: yes

   - name: Relancer le service NginX
     become: true
     service:
        name: nginx
        state: restarted
